### ISSUE TITLE
user authentiation

### ISSUE THREAD

**Issue by sopnaarth** [ankane/blazer-docker#14]
how to add multiple authentication  from ankane/blazer docker pull? I cannot add new user authentiation apart from blazer_username and blazer_password

**Comment by sopnaarth** [comment]
@ankane

**Comment by ankane** [comment]
Hi @sopnaarth, the image only has built-in support for basic authentication, so you'd need to use a reverse proxy like [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy).
