### ISSUE TITLE
Health endpoint not working in 3.1.0

### ISSUE THREAD

**Issue by otherguy** [ankane/blazer-docker#17]
The `/health` endpoint is returning `503` with Blazer 3.1.0.

After a manual `connect!` it would work.

![CleanShot 2024-10-16 at 10 20 23@2x](https://github.com/user-attachments/assets/e27843b2-0300-4f25-9016-40fd87d9c5c9)

```ruby
    routes.append do
      # checks app is up and can connect to database
      # does not check data sources
      # not protected by auth, so do not expose data
      get "health", to: ->(env) {
        if Blazer::Connection.connection.active?
          [200, {}, ["OK"]]
        else
          [503, {}, ["Service Unavailable"]]
        end
      }


      mount Blazer::Engine, at: "/"
```

You probably should also add the `ostruct` gem to your Gemfile to get rid of the deprecation warning and set `RAILS_ENV` to default to `production` in the Docker container :)

**Comment by ankane** [comment]
Hi @otherguy, thanks for reporting. Removed the database check in the commit above and pushed a new image to the `latest` tag.

**Comment by otherguy** [comment]
```
# checks app is up, not database or data sources healthy
```

Actually a much better check and in-line with Kubernetes recommendations _:chefskiss:_

**Comment by otherguy** [comment]
@ankane could you please also push a new tag, eg. `3.1.1` (or overwrite `3.1.0`)? We're only updating to release tags, not `latest`.
